# Generated by Django 4.1 on 2022-09-01 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='foto',
        ),
        migrations.AlterField(
            model_name='hospedagem',
            name='foto',
            field=models.ImageField(null=True, upload_to='Hospedagem', verbose_name='Foto'),
        ),
    ]
